name: Pull Request

on:
  pull_request:
    branches:
      - develop
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Print hello
        run: echo "CI is running"

  build:
    runs-on: macos-latest
    needs: test
    steps:
      - uses: actions/checkout@v4

      - name: Build iOS project
        run: |
          xcodebuild \
            -project CI_CD.xcodeproj \
            -scheme CI_CD \
            -destination 'generic/platform=iOS Simulator' \
            clean build

  unit-test:
    runs-on: macos-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Show available simulators (debug)
        run: |
          xcodebuild \
            -project CI_CD.xcodeproj \
            -scheme CI_CD \
            -showdestinations

      - name: Run unit tests (Mac)
        run: |
          xcodebuild \
            -project CI_CD.xcodeproj \
            -scheme CI_CD \
            -destination 'platform=macOS,arch=arm64,variant=Designed for [iPad,iPhone]' \
            test